version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./application:/application
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php

  php:
    container_name: php
    image: php:fpm
    volumes:
      - ./application:/application