version: '3'

services:

  nginx:
    container_name: nginx
    build: ./services/nginx
    ports:
      - 80:80
    volumes:
      - ./application:/application
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php

  php:
    container_name: php
    build: ./services/php
    environment:
      - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
    volumes:
      - ./application:/application
      - ./services/php/php.ini:/usr/local/etc/php/php.ini