version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./application:/application
      - ./services/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php

  php:
    container_name: php
    build: ./services/php
    volumes:
      - ./application:/application
      - ./services/php/conf.d:/usr/local/etc/php/conf.d
      - ./services/php/php.ini:/usr/local/etc/php/php.ini